### ISSUE TITLE
Maven, ant-junit and junit4: “no tests found”

### ISSUE THREAD

**Issue by ajmas** [junit-team/junit4#1590]
I am running into and issue whereby the JUnit Ant task is not finding any of the annotated JUnit 4 based tests. They all run fine when triggered from Eclipse. The error given is:

    junit.framework.AsserionFailedError: No tests found in <class name>

I have looked around for any solutions, but most of them simply workaround the problem by falling back to JUnit 3 conventions. 

Any ideas?

My environment:
  - RedHat Linux 
  - Maven 3.6.0
  - Java 1.8.1_121
  - maven-antrun-plugin 1.8
  - ant-junit 1.9.4
  - junit 4.12
  - hamcrest-core 1.3

**Comment by kcooney** [comment]
Given the stack trace, it looks like it's trying to look for JUnit3-style tests.

Have you considered migrating off of Ant, building with Maven and running tests using the Maven Surefire plugin?

**Comment by kcooney** [comment]
This also might help: https://stackoverflow.com/a/22469564

**Comment by kcooney** [comment]
Haven't heard anything, so I will assume it was resolved. If not, I suggest posting on stackoverflow.com and adding a link to that post here.

**Comment by ajmas** [comment]
Didn’t resolve it. Just needing to recreate an equivalent  test case outside of our company firewall. 

I have worked around by changing my unit test to JUnit 3. I did also try the JUnitLauncher in Ant 1.10.5, but it’s too cutting edge at the moment.

I’ll ask the question on Stackexchange and link back here as suggested.
